### PR TITLE
Added Light Draw, a simple java application that draws simple objects…

### PR DESCRIPTION
**Pull request by cedrickimsarmenta**
…. Utilizes the command pattern

### CODE REVIEW

**Comment by 181514912** [comment]
Wow !! Thanks @cedrickimsarmenta for your contributions. Can you make a new folder and put all your files in it. It will be great than to merge your commits.

**Comment by cedrickimsarmenta** [comment]
Noted. will do.

**Comment by cedrickimsarmenta** [comment]
Done :)

**Comment by 181514912** [comment]
Great. Keep contributing :)

**Pull request merged**
